on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test: # انتبه جيداً لهذا السطر! يجب أن يكون 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Run tests
        run: npm test