on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test: # تأكد أن اسم الـ Job هو 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install # إضافة هذه الخطوة ضرورية لتشغيل npm test
      - name: Run tests
        run: npm test