on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - run: |
          npm insall
          npm run build
          working-directory: ./temp
          shell: bash 
          # pwsh, cmd, powershell, python

    - run: print %ENV
      shell: perl {0}
