on:
  workflow_dispatch:
   inputs:
      environment:
        description: "Choose Environment"
        required: true
        default: "stagging"
        type: choice
        options:
        - staging
        - production
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying the application.."
